sudo: false
language: php
php:
- 5.6
- 7.0
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install
script:
- mkdir build
- mkdir build/coverage
- php tests/zru.php
